# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!
  GAME_INJECTOR: '{{.TASKFILE_DIR}}/build/debug/game_injector.exe'

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  game_injector:
    desc: 'inject or unload overlay; usage: task game_injector -- inject|unload <pid>'
    cmds:
      - '"{{.GAME_INJECTOR}}" {{.CLI_ARGS}}'
