function(msvc_ifc_search_dirs)
    if (NOT MSVC)
        return()
    endif ()
    _msvc_ifc_search_dirs("${CMAKE_SOURCE_DIR}")
endfunction()

function(_msvc_ifc_search_dirs dir)
    get_property(tgts DIRECTORY "${dir}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach (tgt IN LISTS tgts)
        get_target_property(imported ${tgt} IMPORTED)
        if (imported)
            continue()
        endif ()
        get_target_property(module_sets ${tgt} CXX_MODULE_SETS)
        if (NOT module_sets)
            continue()
        endif ()
        target_compile_options(${tgt} PUBLIC
                "$<BUILD_INTERFACE:/ifcSearchDir$<TARGET_PROPERTY:${tgt},BINARY_DIR>/CMakeFiles/${tgt}.dir>"
        )
    endforeach ()
    get_property(subdirs DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
    foreach (sub IN LISTS subdirs)
        _msvc_ifc_search_dirs("${sub}")
    endforeach ()
endfunction()
